### ISSUE TITLE
'NODE_OPTIONS' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by matt-rose-salesforce** [SalesforceCommerceCloud/sfcc-sample-apps#127]
On windows, when running `yarn build` I see this error:
```
'NODE_OPTIONS' is not recognized as an internal or external command,
```

**Comment by deokkeemin-salesforce** [comment]
Got the same error on Windows. I was able to `yarn build` by adding [cross-env](https://www.npmjs.com/package/cross-env) and modifying the packages/storefront-lwc/package.json as follows:

```diff
-     "build:resources": "NODE_OPTIONS='--experimental-modules --experimental-specifier-resolution=node' node scripts/copy-resources.mjs",
+     "build:resources": "cross-env NODE_OPTIONS=\"--experimental-modules --experimental-specifier-resolution=node\" node scripts/copy-resources.mjs",

-     "start": "NODE_OPTIONS='--experimental-modules --experimental-specifier-resolution=node' node ./scripts/runtime.mjs",
+     "start": "cross-env NODE_OPTIONS=\"--experimental-modules --experimental-specifier-resolution=node\" node ./scripts/runtime.mjs",
```

**Comment by gurpreetsainisalesforce** [comment]
@blittle - Should we make this change to `package.json` to make it work on Windows?

**Comment by blittle** [comment]
Yes, we should be using cross-env

**Comment by emchobg** [comment]
Which version node have you used?

**Comment by matt-rose-salesforce** [comment]
@blittle and @gurpreetsainisalesforce,  When can we let our customers know this will be fixed by?

**Comment by gurpreetsainisalesforce** [comment]
> @blittle and @gurpreetsainisalesforce, When can we let our customers know this will be fixed by?

We will be making this change in our current sprint. The next release should have this change.

**Comment by blittle** [comment]
@matt-rose-salesforce if you get time, mind pulling that branch and verifying it works under windows? I've done so on MacOS. If you don't have time, I'll pull the project and try it out on a windows machine at home.

**Comment by matt-rose-salesforce** [comment]
Hey @blittle I gave it a shot and ran into this error:
```
storefront-lwc: $ cross-env NODE_OPTIONS='--experimental-modules --experimental-specifier-resolution=node' node scripts/copy-resources.mjs
storefront-lwc: internal/modules/cjs/loader.js:1000
storefront-lwc:     throw new ERR_REQUIRE_ESM(filename);
storefront-lwc:     ^
storefront-lwc: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\repositories\sfcc-sample-apps\packages\storefront-lwc\scripts\copy-resources.mjs
storefront-lwc:     at Module.load (internal/modules/cjs/loader.js:1000:11)
storefront-lwc:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
storefront-lwc:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
storefront-lwc:     at internal/main/run_main_module.js:18:47 {
storefront-lwc:   code: 'ERR_REQUIRE_ESM'
storefront-lwc: }
```

**Comment by deokkeemin-salesforce** [comment]
Windows doesn't seem to like single quotation marks. You might have to replace them with double quotes and escape them.

**Comment by syedshehrozhussain** [comment]
@matt-rose-salesforce can you have a look now and tell us if it worked for you? If so, then we can close this.

@blittle

**Comment by matt-rose-salesforce** [comment]
The app is installed via `yarn install` now. I am running into a new and different issue now but I will debug on my own and see if I am missing a new step or configuration that may be introduced since I tested last.

**Comment by syedshehrozhussain** [comment]
> The app is installed via `yarn install` now. I am running into a new and different issue now but I will debug on my own and see if I am missing a new step or configuration that may be introduced since I tested last.

Thank you @matt-rose-salesforce 
let us know if there is an issue. I am closing this for now. If there is an issue with the original issue posted here please feel free to open it or create a new one.

**Comment by matt-rose-salesforce** [comment]
Thanks @syedshehrozhussain . I investigated the issue I was having and it's was related to my OCAPI configuration and unrelated. Thanks to @blittle for getting this fixed.
