### ISSUE TITLE
[HPM] Error occurred while trying to proxy request /assets/favicon.ico from localhost:3000 to http://localhost:3002 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

### ISSUE THREAD

**Issue by prashantkulkarniv** [SalesforceCommerceCloud/sfcc-sample-apps#128]
I am getting two issues,
1) storefront-lwc: [nodemon] app crashed - waiting for file changes before starting...
2) [HPM] Error occurred while trying to proxy request /assets/favicon.ico from localhost:3000 to http://localhost:3002 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

Because of 2nd issue no image or css is loading, even i think APIs are also not loading.

Please let me know if anyone else also faced same issue and fixed it?

Thanks,
PK

**Comment by blittle** [comment]
You might have a stray node service running. Try running `pkill node` and then restarting the app.

**Comment by syedshehrozhussain** [comment]
@prashantkulkarniv can you have a look now and tell us if you are still facing this issue? So that we could close this if there is no issue anymore.

**Comment by prashantkulkarniv** [comment]
@syedshehrozhussain yes please close this.

**Comment by syedshehrozhussain** [comment]
No longer an issue. Thanks for checking @prashantkulkarniv 

Closing this now.
