### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by emchobg** [SalesforceCommerceCloud/sfcc-sample-apps#175]
Hi Team,
I noticed that currently if default locale is not enabled - the calls are failing, there should be an option to allow either configuration of the locale or to be added in the router, so the requests can properly send the correct locale. 

Regards

**Comment by blittle** [comment]
Hi @emchobg! Could you give a more specific example of what you are looking for? We also just released a new version that changed the router implementation. See https://github.com/SalesforceCommerceCloud/sfcc-sample-apps/releases/tag/1.0.0-alpha.2
