### ISSUE TITLE
Platform Specific Dependencies | Windows

### ISSUE THREAD

**Issue by PremSolanki** [SalesforceCommerceCloud/sfcc-sample-apps#177]
Hi All

Is there any platform specific dependency in order to execute the app commands?

-  Window users will face issue “'NODE_OPTIONS' is not recognized as an internal or external command, operable program or batch file.”

**For that we are now using cross-env before NODE_OPTIONS.**

- When i'm running the 'integration' branch in window machine ,not able to get the Session Property context.getSessionProperty('basketId');

[Giving Error : No basket has been created yet.]
and showing empty cart page but the same code on Mac is working fine.

**Comment by blittle** [comment]
@PremSolanki this is fixed on the integration branch, and we'll be releasing to master in the near future.

**Comment by syedshehrozhussain** [comment]
If this is fixed, can we close this? @PremSolanki and @blittle

**Comment by blittle** [comment]
Yup. It should be fixed with https://github.com/SalesforceCommerceCloud/sfcc-sample-apps/releases/tag/1.0.0-alpha.2
