### ISSUE TITLE
Authorization Token has expired

### ISSUE THREAD

**Issue by rahimali786** [SalesforceCommerceCloud/sfcc-sample-apps#218]
Hi Team,

I am trying to deploy the sample application, the home page is displayed but when i click on any Product category, i am seeing following error on console. Any help is really appreciated

Authorization Token has expired
logger.ts:39 Error in requestWithTokenRefresh() Error: 404 Not Found
    at Object.<anonymous> (C:\Work\Projects\Comerce_Cloud\Apps_with_APIs\MFRM\SFCC_Sample_APP\sfcc-sample-apps\node_modules\commerce-sdk\dist\helpers.js:34:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Work\Projects\Comerce_Cloud\Apps_with_APIs\MFRM\SFCC_Sample_APP\sfcc-sample-apps\node_modules\tslib\tslib.js:110:62)

**Comment by echessman** [comment]
Hello @rahimali786 I have not seen this error before. I was receiving the following error 

```
Error in requestWithTokenRefresh() ResponseError: 403 Forbidden
storefront-lwc:     at Object.<anonymous> (/Users/echessman/Projects/sfcc-sample-apps/node_modules/commerce-sdk/dist/helpers.js:34:13)
storefront-lwc:     at Generator.next (<anonymous>)
storefront-lwc:     at fulfilled (/Users/echessman/Projects/sfcc-sample-apps/node_modules/tslib/tslib.js:110:62) {
```

This was fixed with the following PR https://github.com/SalesforceCommerceCloud/sfcc-sample-apps/pull/220

Can you see if that resolves the issue?

**Comment by rahimali786** [comment]
Thanks for he reply. I tried but no luck.

Seems to me some connection issue when i tried to hit the request URL in Apollo GraphQL "http://localhost:3000/api" I got following error.
"error": "Failed to fetch schema. Please check your connection"

**Comment by jbegleiter-sf** [comment]
Hey @rahimali786 ,

We have validated that we do not see this particular error against the latest release. It looks like you may be having an issue related to your GraphQL playground. If so please try starting the app in development mode.

For future assistance please utilize the CCDC forums.

Cheers,
Josh
