### ISSUE TITLE
Authorization Token has expired undefined

### ISSUE THREAD

**Issue by bsilverm** [SalesforceCommerceCloud/sfcc-sample-apps#225]
This issue prevents the sample app from running properly when run from within VSCode.  Anything requiring an auth token (ie - issuing a product search) fails with the following:

```
storefront-lwc: Authorization Token has expired undefined
storefront-lwc: Error in requestWithTokenRefresh() TypeError: next is not a function
```
Full output below:

C:\Program Files\nodejs\npm.cmd run-script start:dev

> sampleapp@1.0.0-alpha.1 start:dev c:\Users\bsilverman\Desktop\sampleapp
> lerna run start:dev --scope storefront-lwc --stream
lerna notice cli v3.20.2
lerna notice filter including "storefront-lwc"
lerna info filter [ 'storefront-lwc' ]
lerna info Executing command in 1 package: "yarn run start:dev"
storefront-lwc: yarn run v1.22.4
storefront-lwc: $ run-p watch:client watch:server watch:scss
storefront-lwc: > storefront-lwc@1.0.0-alpha.2 watch:scss c:\Users\bsilverman\Desktop\sampleapp\packages\storefront-lwc
storefront-lwc: > run-p -c --aggregate-output watch:lwc:scss watch:public:scss
storefront-lwc: > storefront-lwc@1.0.0-alpha.2 watch:client c:\Users\bsilverman\Desktop\sampleapp\packages\storefront-lwc
storefront-lwc: > rollup --config ./scripts/rollup.config.js --watch
storefront-lwc: > storefront-lwc@1.0.0-alpha.2 watch:server c:\Users\bsilverman\Desktop\sampleapp\packages\storefront-lwc
storefront-lwc: > nodemon
storefront-lwc: [nodemon] 2.0.3
storefront-lwc: [nodemon] to restart at any time, enter `rs`
storefront-lwc: [nodemon] watching path(s): ..\@sfcc-core\**\* ..\@sfcc-bff\**\* scripts\**\*
storefront-lwc: [nodemon] watching extensions: js
storefront-lwc: [nodemon] starting `cross-env NODE_ENV=development node -r esm --nolazy --inspect=9229 ./scripts/runtime.js`
storefront-lwc: rollup v2.6.1
storefront-lwc: bundles c:\Users\bsilverman\Desktop\sampleapp\packages\storefront-lwc\src\index.js → dist...
storefront-lwc: Debugger listening on ws://127.0.0.1:9229/8ed05831-8c17-42e6-8897-57bd78b2c0ac
storefront-lwc: For help, see: https://nodejs.org/en/docs/inspector
storefront-lwc: Create the Core instance used to register services and extensions.
storefront-lwc: registerService(Symbol(API Configuration Service))
storefront-lwc: registerService(Symbol(Logger Service))
storefront-lwc: registerService(Symbol(Node Express))
storefront-lwc: CoreGraphQL.constructor()
storefront-lwc: Start CoreGraphQL
storefront-lwc: ProductAPI.constructor(core)
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: ProductAPI.typeDefs() {
storefront-lwc:   kind: 'Document',
storefront-lwc:   definitions: [
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeExtension',
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     }
storefront-lwc:   ],
storefront-lwc:   loc: { start: 0, end: 1828 }
storefront-lwc: } {
storefront-lwc:   kind: 'Document',
storefront-lwc:   definitions: [
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeExtension',
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'InputObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     },
storefront-lwc:     {
storefront-lwc:       kind: 'ObjectTypeDefinition',
storefront-lwc:       description: undefined,
storefront-lwc:       name: [Object],
storefront-lwc:       interfaces: [],
storefront-lwc:       directives: [],
storefront-lwc:       fields: [Array]
storefront-lwc:     }
storefront-lwc:   ],
storefront-lwc:   loc: { start: 0, end: 1097 }
storefront-lwc: }
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: ProductAPI.getResolvers() {
storefront-lwc:   COMMERCE_API_PATH: '/api',
storefront-lwc:   COMMERCE_CLIENT_API_SITE_ID: 'RefArch',
storefront-lwc:   COMMERCE_CLIENT_CLIENT_ID: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
storefront-lwc:   COMMERCE_CLIENT_REALM_ID: 'abcd',
storefront-lwc:   COMMERCE_CLIENT_INSTANCE_ID: 's01',
storefront-lwc:   COMMERCE_CLIENT_ORGANIZATION_ID: 'f_ecom_abcd_s01',
storefront-lwc:   COMMERCE_CLIENT_SHORT_CODE: 'xxxxxxx',
storefront-lwc:   COMMERCE_LOG_LEVEL: 1,
storefront-lwc:   COMMERCE_SESSION_SECRET: 'SomeSecretValue'
storefront-lwc: }
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: basketAPI.constructor(core)
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: basketAPI.typeDefs() [object Object]
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: basketAPI.getResolvers() [object Object]
storefront-lwc: ===========================
storefront-lwc: ===========================
storefront-lwc: CoreGraphQL apolloServer middleware applied to express!
storefront-lwc: Is Express Registered? true
storefront-lwc: Is GraphQL Registered? true
storefront-lwc: ======== Example SFRA runtime ========
storefront-lwc: {} 🌩 Client Server up on ==============> http://localhost:3000 <=========== Client UI ========== 🌩
storefront-lwc: {} 🚀 Apollo GraphQL Server up on ======> http://localhost:3000/api <=== Apollo GraphQL ===== 🚀
storefront-lwc: Authorization Token has expired undefined
storefront-lwc: Error in requestWithTokenRefresh() TypeError: next is not a function
storefront-lwc:     at attempt (C:\Users\bsilverman\Desktop\sampleapp\node_modules\passport\lib\middleware\authenticate.js:190:34)
storefront-lwc:     at authenticate (C:\Users\bsilverman\Desktop\sampleapp\node_modules\passport\lib\middleware\authenticate.js:367:7)
storefront-lwc:     at C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql-passport\lib\buildContext.js:33:12
storefront-lwc:     at new Promise (<anonymous>)
storefront-lwc:     at promisifiedAuthentication (C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql-passport\lib\buildContext.js:23:11)
storefront-lwc:     at Object.authenticate (C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql-passport\lib\buildContext.js:89:14)
storefront-lwc:     at C:\Users\bsilverman\Desktop\sampleapp\packages\@sfcc-core\core-graphql\dist\core-graphql.cjs.development.js:92:40
storefront-lwc:     at getUserFromContext (C:\Users\bsilverman\Desktop\sampleapp\packages\@sfcc-core\core-graphql\dist\core-graphql.cjs.development.js:99:6)
storefront-lwc:     at getSearchClient (C:\Users\bsilverman\Desktop\sampleapp\packages\@sfcc-bff\productapi\src\api\schema\productSearchResolvers.js:19:15)
storefront-lwc:     at C:\Users\bsilverman\Desktop\sampleapp\packages\@sfcc-bff\productapi\src\api\schema\productSearchResolvers.js:61:36
storefront-lwc:     at C:\Users\bsilverman\Desktop\sampleapp\packages\@sfcc-core\core-graphql\dist\core-graphql.cjs.development.js:271:30
storefront-lwc:     at _catch (C:\Users\bsilverman\Desktop\sampleapp\packages\@sfcc-core\core-graphql\dist\core-graphql.cjs.development.js:60:18)
storefront-lwc:     at requestWithTokenRefresh (C:\Users\bsilverman\Desktop\sampleapp\packages\@sfcc-core\core-graphql\dist\core-graphql.cjs.development.js:270:28)
storefront-lwc:     at searchProduct (C:\Users\bsilverman\Desktop\sampleapp\packages\@sfcc-bff\productapi\src\api\schema\productSearchResolvers.js:42:12)
storefront-lwc:     at productSearch (C:\Users\bsilverman\Desktop\sampleapp\packages\@sfcc-bff\productapi\src\api\schema\productSearchResolvers.js:72:38)
storefront-lwc:     at C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql-extensions\dist\index.js:133:26
storefront-lwc:     at resolveFieldValueOrError (C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql\execution\execute.js:467:18)
storefront-lwc:     at resolveField (C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql\execution\execute.js:434:16)
storefront-lwc:     at executeFields (C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql\execution\execute.js:275:18)
storefront-lwc:     at executeOperation (C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql\execution\execute.js:219:122)
storefront-lwc:     at executeImpl (C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql\execution\execute.js:104:14)
storefront-lwc:     at Object.execute (C:\Users\bsilverman\Desktop\sampleapp\node_modules\graphql\execution\execute.js:64:35)
storefront-lwc:     at C:\Users\bsilverman\Desktop\sampleapp\node_modules\apollo-server-core\dist\requestPipeline.js:241:48
storefront-lwc:     at Generator.next (<anonymous>)
storefront-lwc:     at C:\Users\bsilverman\Desktop\sampleapp\node_modules\apollo-server-core\dist\requestPipeline.js:8:71
storefront-lwc:     at new Promise (<anonymous>)
storefront-lwc:     at C:\Users\bsilverman\Desktop\sampleapp\node_modules\apollo-server-core\dist\requestPipeline.js:4:12
storefront-lwc:     at execute (C:\Users\bsilverman\Desktop\sampleapp\node_modules\apollo-server-core\dist\requestPipeline.js:220:20)
storefront-lwc:     at Object.<anonymous> (C:\Users\bsilverman\Desktop\sampleapp\node_modules\apollo-server-core\dist\requestPipeline.js:160:42)
storefront-lwc:     at Generator.next (<anonymous>)
storefront-lwc:     at fulfilled (C:\Users\bsilverman\Desktop\sampleapp\node_modules\apollo-server-core\dist\requestPipeline.js:5:58)
storefront-lwc:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
storefront-lwc: LiveReload enabled
storefront-lwc: (!) Circular dependency
storefront-lwc: src\modules\commerce\categoryRefinement\categoryRefinement.js -> src\modules\commerce\categoryRefinement\categoryRefinement.html -> src\modules\commerce\categoryRefinement\categoryRefinement.js
storefront-lwc: created dist in 38s

**Comment by bsilverm** [comment]
It looks like the issue is not Windows specific, as others have run in to the same issue on OSX.. though not clear on what influences whether the issue happens or not.

**Comment by jbegleiter-sf** [comment]
This was resolved in the latest version of sample app. Please pull master and try again.
