### ISSUE TITLE
import gql from 'graphql-tag' => Error: The importee argument must be a valid LWC module name

### ISSUE THREAD

**Issue by vsanse** [SalesforceCommerceCloud/sfcc-sample-apps#239]
Hi,

I accidentally deleted my `yarn.lock` file and installed all dependencies by running `yarn` again. This created a new `yarn.lock` file and when I tried running project again via `yarn start:dev` I got the following error:
```js
storefront-lwc: rollup v2.21.0
storefront-lwc: bundles /Users/vissanas/Documents/Test/sfcc-sample-apps/packages/storefront-lwc/src/index.js → dist...
storefront-lwc: npm WARN lifecycle The node binary used for scripts is /var/folders/sj/vw_jx9qn71v2vwhrhmrnrwvs67gj_7/T/yarn--1594454362848-0.4914796472812635/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
storefront-lwc: [!] (plugin rollup-plugin-lwc-compiler) TypeError: The importee argument must be a valid LWC module name. Received "/Users/vissanas/Documents/Test/sfcc-sample-apps/node_modules/graphql/language/parser.mjs"
storefront-lwc: TypeError: The importee argument must be a valid LWC module name. Received "/Users/vissanas/Documents/Test/sfcc-sample-apps/node_modules/graphql/language/parser.mjs"
storefront-lwc:     at resolveModule (/Users/vissanas/Documents/Test/sfcc-sample-apps/node_modules/@lwc/module-resolver/src/index.ts:205:15)
storefront-lwc:     at Object.resolveId (/Users/vissanas/Documents/Test/sfcc-sample-apps/packages/storefront-lwc/node_modules/@lwc/rollup-plugin/src/index.js:74:28)
storefront-lwc:     at /Users/vissanas/Documents/Test/sfcc-sample-apps/packages/storefront-lwc/node_modules/rollup/dist/shared/rollup.js:18233:25
```

**Comment by dorgelesn** [comment]
Hello,

The `yarn.lock` file ensures consistency across installations regarding project dependencies and sub-dependencies.
> Yarn needs to store exactly which versions of each dependency were installed

You have to restore the deleted file in order to make the script work.

**Comment by vsanse** [comment]
Hey @dorgelesn ,

Thanks for the response.
I get that yarn.lock is maintaining all the dependencies' versions but was curious what version is causing LWC to not recognize gql as a valid module as I did not upgrade LWC engine or module resolver. Is it something with rollup?

**Comment by jbegleiter-sf** [comment]
Hey @vsanse ,

Are you still experiencing this issue with the latest version of the project?

Cheers,
Josh

**Comment by vsanse** [comment]
Yes. This is still there.

**Comment by jbegleiter-sf** [comment]
@vsanse can you provide environment information and steps to reproduce? We are unable to reproduce this on our end.

**Comment by vsanse** [comment]
I'm working on MacOS 10.14 mojave, nodejs 12.16
Steps:
1. Take a fresh pull of the repo
2. Delete the yarn.lock file
3. run `yarn`
4. run `yarn build`
You will see the error in terminal.

**Comment by jbegleiter-sf** [comment]
Hey @vsanse ,

I did a brief investigation here. There are many differences between the yarn.lock when you remove it and compare with master. Trying to hunt down these would take significant effort. For now our guidance is to use the yarn.lock that comes with this package. Should we update it in the future we'll revisit this thread.

Cheers,
Josh
