### ISSUE TITLE
Is it possible to get  original data .i.e my site data( eg: funi ), i have all the details like organizationid, client id and so on ,but when i use my details also the app is always showing dummy data of clothes, in the sample app of LWC, how can i get my original data.

### ISSUE THREAD

**Issue by saivenkatesh48** [SalesforceCommerceCloud/sfcc-sample-apps#242]
**2,. another question is which URL, we need to call in the sample to set to COMMERCE_API_PATH ,
to get Product Details (**Login api** :https://{shortCode}.api.commercecloud.salesforce.com/customer/shopper-customers/v1/organizations/{organizationId}/customers/actions/login
or **Prodcut api**
https://{shortCode}.api.commercecloud.salesforce.com/product/shopper-products/{version}, 
if we need to call both how can we call both at a same time.**

3.Is the sample app suitable for Ios Mobile app or any Mobile app why i am asking is , in sample app they mention like this in html, **_<meta name="apple-mobile-web-app-capable" content="yes" />_**.
4.My requirement is i need sample app which suits mobile app.

**Comment by jbegleiter-sf** [comment]
Followed up offline
