### ISSUE TITLE
Watch

### ISSUE THREAD

**Issue by C-Lacerda** [SalesforceCommerceCloud/sfcc-sample-apps#248]
Hi @echessman, first of all, it is a very good start, I really appreciate that. But unfortunately the "watch" seems to be not working.
I mean, I can see that once you performe "yarn start:dev" it already has some watches, but even if that, if I do any change on SCSS, JS or templates, I need to compile all it again every time, is it ok or it should be more reactive? There is any way to keep it watching SCSS, JS or templates changes?

**Comment by echessman** [comment]
With the release of the PWA kit this repo is being archived and is no longer in development. Please see https://github.com/SalesforceCommerceCloud/pwa-kit for using Salesforce Commerce APIs to build a headless shopping experience
